# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JARVISUI(object):
    def setupUi(self, JARVISUI):
        JARVISUI.setObjectName("JARVISUI")
        JARVISUI.resize(1070, 785)
        self.centralwidget = QtWidgets.QWidget(JARVISUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1061, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("iron.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(700, 650, 151, 51))
        self.pushButton.setStyleSheet("background-color: rgb(255, 91, 70);\n"
"background-color: rgb(255, 32, 17);\n"
"font: 12pt \"MS Sans Serif\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(872, 647, 141, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 239, 60);\n"
"font: 12pt \"MS Sans Serif\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 371, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("iron2.jfif"))
        self.label_2.setObjectName("label_2")
        JARVISUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JARVISUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        JARVISUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JARVISUI)
        self.statusbar.setObjectName("statusbar")
        JARVISUI.setStatusBar(self.statusbar)

        self.retranslateUi(JARVISUI)
        QtCore.QMetaObject.connectSlotsByName(JARVISUI)

    def retranslateUi(self, JARVISUI):
        _translate = QtCore.QCoreApplication.translate
        JARVISUI.setWindowTitle(_translate("JARVISUI", "MainWindow"))
        self.pushButton.setText(_translate("JARVISUI", "RUN"))
        self.pushButton_2.setText(_translate("JARVISUI", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JARVISUI = QtWidgets.QMainWindow()
    ui = Ui_JARVISUI()
    ui.setupUi(JARVISUI)
    JARVISUI.show()
    sys.exit(app.exec_())
